name: CI

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.18.0'

    - name: Install dependencies
      run: npm ci 

    - name: Get version from package.json
      id: pkg
      run: echo "::set-output name=version::$(node -p "require('./package.json').version")"
      
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1.0.0
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
      with:
        tag_name: ${{ steps.pkg.outputs.version }}
        release_name: Release ${{ steps.pkg.outputs.version }}
        draft: false
        prerelease: false

    - name: Build
      run: npm run publish
